# Generated by Django 3.0.5 on 2020-05-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categorias',
            field=models.CharField(choices=[('programacao', 'Programação'), ('eletronica', 'Eletrônica')], default='programacao', max_length=12),
        ),
    ]
