# Generated by Django 3.0.5 on 2020-05-22 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='teste',
        ),
    ]
