# Generated by Django 3.0.5 on 2020-05-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='Status',
        ),
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('PY', 'Python'), ('DJ', 'Django'), ('PG', 'Programação'), ('IoT', 'Internet das Coisas'), ('POO', 'Programação Orientada a Objetos'), ('BD', 'Banco de dados')], default='PG', max_length=3),
        ),
    ]
