# Generated by Django 3.0.5 on 2020-05-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200522_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ativado',
            field=models.BooleanField(default=True),
        ),
    ]
